name: actions
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
  pull_request:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
jobs:
  qemu-user-static:
    environment: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        run: |
          echo "DOCKER_REPO=docker.io/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - name: Build
        run: |
          wget --content-disposition http://ftp.de.debian.org/debian/pool/main/q/qemu/qemu-user-static_${{ vars.ORIGIN_VERSION }}_amd64.deb
          dpkg-deb -R qemu-user-static_*.deb releases
          ./run.sh -t "${{ vars.VERSION }}" -r "${{ vars.GITHUB_REPOSITORY }}" -d "${{ vars.DOCKER_REPO }}"
      #- name: Test
        #run: ./test.sh -d "${{ vars.DOCKER_REPO }}"
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ vars.DOCKER_SERVER }}
          docker push --all-tags ${{ vars.DOCKER_REPO }}
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          name: "v${{ vars.VERSION }}"
          tag: "v${{ vars.VERSION }}"
          body: |
            # `qemu-*-static` @ ${{ vars.VERSION }}
          artifacts: "releases/usr/bin/*.tar.gz,releases/usr/bin/qemu-*-static"
          draft: false
          prerelease: false
          token: ${{ secrets.GH_TOKEN }}
